import{a as f,S as b,i as l}from"./assets/vendor-cd34AgZ1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const w="45522161-5a4b1fd5e13efcf8857e5e3e0";f.defaults.baseURL="https://pixabay.com/api/";const v=async(e,o=1)=>{try{return(await f.get("",{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15}})).data}catch(r){throw console.error("Error fetching images:",r),r}},g=document.querySelector(".gallery"),S=new b(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.8}),P=e=>`<li class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
                <img
                class="gallery-image"
                src="${e.webformatURL}"
                data-source="${e.largeImageURL}"
                alt="${e.tags}"
                />
            </a>
            <div class="info">
                <p class="text-info">Likes: <span class="number-info">${e.likes}</span></p>
                <p class="text-info">Views: <span class="number-info">${e.views}</span></p>
                <p class="text-info">Comments: <span class="number-info">${e.comments}</span></p>
                <p class="text-info">Downloads: <span class="number-info">${e.downloads}</span></p>
            </div>
        </li>`,h=async(e,o=!1)=>{if(o&&(g.innerHTML=""),e.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const r=e.map(P).join("");g.insertAdjacentHTML("beforeend",r),S.refresh()},m=document.querySelector(".search-form"),p=document.querySelector(".loader"),a=document.querySelector(".load-more"),y=document.querySelector(".gallery");let n=1,i="",d=0;const q=()=>{p.classList.remove("hidden")},R=()=>{p.classList.add("hidden")},$=e=>{e.preventDefault(),i=m.elements.user_query.value.trim(),i&&(n=1,L(i,n))},L=async(e,o)=>{q();try{const r=await v(e,o);if(d=r.totalHits,d===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a.classList.add("hidden"),y.innerHTML="";return}o===1?h(r.hits,!0):(h(r.hits,!1),E()),m.reset(),x()}catch(r){console.error("Error fetching images:",r),l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{R()}},x=()=>{const e=Math.ceil(d/15);n>=e?(a.classList.add("hidden"),l.info({message:"We’re sorry, but you’ve reached the end of search results.",position:"topRight"})):a.classList.remove("hidden")},M=()=>{n++,L(i,n)},E=()=>{const{height:e}=y.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};m.addEventListener("submit",$);a.addEventListener("click",M);a.classList.add("hidden");
//# sourceMappingURL=index.js.map
